version: '3.7'

services:
    database:
        container_name: ecf.studi.db
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MARIADB_ROOT_HOST: '%'
            MARIADB_ROOT_PASSWORD: 'admin'
        ports:
            - '13305:3306'
